name: form_app
description: Official Interface to NIG network and best practices
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  intl: ^0.19.0
  http: ^0.13.0
  json_annotation: any
  english_words: ^4.0.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  chaquopy: ^0.0.19
  provider: ^6.0.3
  shared_preferences: ^2.2.2
  path_provider: ^2.0.11
  fl_chart: ^0.63.0
  stop_watch_timer: ^3.1.0+4
  url_launcher: ^6.1.14
  restart_app: ^1.2.1
  connectivity_plus: ^5.0.2
  rename: ^3.0.2
  flutter_local_notifications: ^17.0.0
  cron: ^0.6.0
  rate_in_stars: ^0.0.3
  web3dart: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  build_runner: ^2.1.8
  flutter_lints: ^2.0.1
  meta: ^1.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/nig_data.json
    - assets/nig_script.py
    - assets/nig_decrypt.py
    - assets/contract_abi.json
